"""Clean-room TD3+BC with optional HUBL Bellman targets.

This module follows the algorithmic equations from Fujimoto & Gu (2021):
states are normalized, the critic uses clipped double-Q targets with target
policy smoothing, and the delayed actor objective is

    - alpha / mean(|Q(s, pi(s))|) * mean(Q(s, pi(s)))
    + mean((pi(s) - a_dataset)^2).

HUBL changes only the critic continuation target.  Given a per-transition
heuristic ``h_next`` and trust weight ``lambda``, the usual TD continuation
``Q_target`` is replaced by ``lambda*h_next + (1-lambda)*Q_target``.  Setting
lambda to zero exactly recovers TD3+BC.

For datasets collected under actuator perturbations, the learner keeps the
commanded policy action and the action actually executed by the environment as
two explicit channels.  ``action_pairing`` determines which channel supervises
the transition critic and which channel is used by the actor's behavior-cloning
term:

``executed_executed``
    Standard offline RL: both critic and BC use the executed dataset action.
``commanded_commanded``
    Naive relabeling control: both critic and BC use the clean command, even
    though the recorded transition was generated by a different action.
``executed_commanded``
    Dual-action variant: critic uses the causally correct executed action while
    BC imitates the behavior policy's clean command.

The optional noise-marginalized variant gives that last pairing its deployment
semantics.  The actor emits a command ``u`` but its Q objective and its Bellman
target average the physical-action critic over a fixed antithetic quadrature,

    E_eps Q(s, clip(u + eps)),  eps ~ Uniform([-beta, beta]^d).

The default estimator redraws per-state antithetic samples from two dedicated
reproducible actor/target RNG streams; a frozen-point quadrature remains an
explicit ablation.  Both keep the extra critic cost visible.  With ``beta=0``
the equations reduce to ordinary TD3+BC with executed-action critic targets and
commanded-action BC.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

import numpy as np
import torch
from torch import nn


ACTION_PAIRINGS = (
    "executed_executed",
    "commanded_commanded",
    "executed_commanded",
)

EXECUTION_NOISE_SCHEMES = (
    "resampled_antithetic",
    "fixed_antithetic",
)
EXECUTION_NOISE_TWIN_REDUCTIONS = (
    "min_of_expectations",
    "expectation_of_min",
)
EXECUTION_NOISE_STREAMS = ("target", "actor")


def fixed_antithetic_uniform_samples(
    action_dim: int,
    sample_count: int,
    beta: float,
    seed: int,
) -> np.ndarray:
    """Construct a frozen empirical quadrature for iid uniform action noise.

    Every nonzero point is paired with its negative, so the empirical first
    moment is exactly zero.  An odd sample count additionally contains the
    midpoint.  The seed controls only this once-per-run construction; samples
    are never redrawn inside an update.  Returning action-scaled perturbations
    (rather than normalized nodes) makes the saved sample table auditable.
    """

    if action_dim <= 0:
        raise ValueError("action_dim must be positive")
    if sample_count <= 0:
        raise ValueError("sample_count must be positive")
    if beta < 0.0 or not np.isfinite(beta):
        raise ValueError("beta must be finite and non-negative")
    pair_count = sample_count // 2
    rng = np.random.default_rng(int(seed))
    positive_half = rng.uniform(
        -beta, beta, size=(pair_count, action_dim)
    ).astype(np.float32)
    pieces = []
    if sample_count % 2:
        pieces.append(np.zeros((1, action_dim), dtype=np.float32))
    if pair_count:
        pieces.extend((positive_half, -positive_half))
    samples = np.concatenate(pieces, axis=0)
    if samples.shape != (sample_count, action_dim):
        raise AssertionError("fixed antithetic sample construction changed shape")
    return samples


def make_mlp(input_dim: int, output_dim: int, hidden_dim: int, depth: int) -> nn.Sequential:
    if depth < 1:
        raise ValueError("depth must be positive")
    layers = []
    previous = input_dim
    for _ in range(depth):
        layers.extend((nn.Linear(previous, hidden_dim), nn.ReLU()))
        previous = hidden_dim
    layers.append(nn.Linear(previous, output_dim))
    return nn.Sequential(*layers)


class DeterministicPolicy(nn.Module):
    def __init__(
        self,
        observation_dim: int,
        action_dim: int,
        hidden_dim: int,
        depth: int,
        max_action: float,
    ):
        super().__init__()
        self.network = make_mlp(observation_dim, action_dim, hidden_dim, depth)
        self.max_action = float(max_action)

    def forward(self, observations: torch.Tensor) -> torch.Tensor:
        return self.max_action * torch.tanh(self.network(observations))


class TwinCritic(nn.Module):
    def __init__(self, observation_dim: int, action_dim: int, hidden_dim: int, depth: int):
        super().__init__()
        input_dim = observation_dim + action_dim
        self.q1 = make_mlp(input_dim, 1, hidden_dim, depth)
        self.q2 = make_mlp(input_dim, 1, hidden_dim, depth)

    def both(
        self, observations: torch.Tensor, actions: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        inputs = torch.cat((observations, actions), dim=-1)
        return self.q1(inputs).squeeze(-1), self.q2(inputs).squeeze(-1)

    def q1_only(self, observations: torch.Tensor, actions: torch.Tensor) -> torch.Tensor:
        return self.q1(torch.cat((observations, actions), dim=-1)).squeeze(-1)


@dataclass(frozen=True)
class TD3BCConfig:
    observation_dim: int
    action_dim: int
    hidden_dim: int = 256
    depth: int = 2
    max_action: float = 1.0
    discount: float = 0.99
    tau: float = 0.005
    policy_noise: float = 0.2
    noise_clip: float = 0.5
    policy_frequency: int = 2
    alpha: float = 2.5
    actor_learning_rate: float = 3e-4
    critic_learning_rate: float = 3e-4
    q_scale_epsilon: float = 1e-6
    action_pairing: str = "executed_executed"
    marginalize_execution_noise: bool = False
    execution_noise_beta: float = 0.0
    execution_noise_samples: int = 1
    execution_noise_seed: int = 314159
    execution_noise_scheme: str = "fixed_antithetic"
    execution_noise_twin_reduction: str = "min_of_expectations"

    def __post_init__(self) -> None:
        if self.observation_dim <= 0 or self.action_dim <= 0:
            raise ValueError("observation_dim and action_dim must be positive")
        if self.max_action <= 0:
            raise ValueError("max_action must be positive")
        if self.policy_frequency <= 0:
            raise ValueError("policy_frequency must be positive")
        if not 0.0 <= self.tau <= 1.0:
            raise ValueError("tau must lie in [0, 1]")
        if self.action_pairing not in ACTION_PAIRINGS:
            raise ValueError(
                f"action_pairing must be one of {ACTION_PAIRINGS}, got "
                f"{self.action_pairing!r}"
            )
        if self.execution_noise_scheme not in EXECUTION_NOISE_SCHEMES:
            raise ValueError(
                "execution_noise_scheme must be one of "
                f"{EXECUTION_NOISE_SCHEMES}, got {self.execution_noise_scheme!r}"
            )
        if (
            self.execution_noise_twin_reduction
            not in EXECUTION_NOISE_TWIN_REDUCTIONS
        ):
            raise ValueError(
                "execution_noise_twin_reduction must be one of "
                f"{EXECUTION_NOISE_TWIN_REDUCTIONS}, got "
                f"{self.execution_noise_twin_reduction!r}"
            )
        if self.execution_noise_samples <= 0:
            raise ValueError("execution_noise_samples must be positive")
        if self.execution_noise_beta < 0.0 or not np.isfinite(
            self.execution_noise_beta
        ):
            raise ValueError("execution_noise_beta must be finite and non-negative")
        if self.execution_noise_seed < 0:
            raise ValueError("execution_noise_seed must be non-negative")
        if self.marginalize_execution_noise:
            if self.action_pairing != "executed_commanded":
                raise ValueError(
                    "noise marginalization requires action_pairing="
                    "'executed_commanded': critic data are executed actions and "
                    "BC targets are commanded actions"
                )
            if (
                self.execution_noise_scheme == "resampled_antithetic"
                and self.execution_noise_beta > 0.0
                and self.execution_noise_samples % 2 != 0
            ):
                raise ValueError(
                    "resampled_antithetic requires an even "
                    "execution_noise_samples count K=2m"
                )
        elif self.execution_noise_samples != 1 or self.execution_noise_beta != 0.0:
            raise ValueError(
                "disabled noise marginalization requires one zero-noise sample"
            )


class TD3BCAgent:
    """TD3+BC learner whose Bellman target optionally uses fixed HUBL fields."""

    def __init__(
        self,
        config: TD3BCConfig,
        device: torch.device,
        observation_mean: np.ndarray,
        observation_std: np.ndarray,
    ):
        self.config = config
        self.device = device
        mean = np.asarray(observation_mean, dtype=np.float32).reshape(1, -1)
        std = np.asarray(observation_std, dtype=np.float32).reshape(1, -1)
        expected_shape = (1, config.observation_dim)
        if mean.shape != expected_shape or std.shape != expected_shape:
            raise ValueError(f"normalizer arrays must have shape {expected_shape}")
        if np.any(std <= 0.0) or not np.all(np.isfinite(mean)) or not np.all(np.isfinite(std)):
            raise ValueError("normalizer must be finite and have strictly positive std")
        self.observation_mean = torch.as_tensor(mean, dtype=torch.float32, device=device)
        self.observation_std = torch.as_tensor(std, dtype=torch.float32, device=device)

        self.actor = DeterministicPolicy(
            config.observation_dim,
            config.action_dim,
            config.hidden_dim,
            config.depth,
            config.max_action,
        ).to(device)
        self.actor_target = copy.deepcopy(self.actor).requires_grad_(False).to(device)
        self.critic = TwinCritic(
            config.observation_dim,
            config.action_dim,
            config.hidden_dim,
            config.depth,
        ).to(device)
        self.critic_target = copy.deepcopy(self.critic).requires_grad_(False).to(device)
        self.actor_optimizer = torch.optim.Adam(
            self.actor.parameters(), lr=config.actor_learning_rate
        )
        self.critic_optimizer = torch.optim.Adam(
            self.critic.parameters(), lr=config.critic_learning_rate
        )
        self.execution_noise_generators: Dict[str, torch.Generator] = {}
        maximum_seed = (1 << 63) - 1
        self.execution_noise_stream_seeds = {
            "target": int(config.execution_noise_seed % maximum_seed),
            "actor": int((config.execution_noise_seed + 1) % maximum_seed),
        }
        if config.execution_noise_scheme == "fixed_antithetic":
            execution_noise = fixed_antithetic_uniform_samples(
                config.action_dim,
                config.execution_noise_samples,
                config.execution_noise_beta,
                config.execution_noise_seed,
            )
            self.execution_noise: Optional[torch.Tensor] = torch.as_tensor(
                execution_noise, dtype=torch.float32, device=device
            )
        else:
            self.execution_noise = None
            for stream in EXECUTION_NOISE_STREAMS:
                generator = torch.Generator(device=device)
                generator.manual_seed(self.execution_noise_stream_seeds[stream])
                self.execution_noise_generators[stream] = generator
        self.execution_noise_draw_calls = {
            stream: 0 for stream in EXECUTION_NOISE_STREAMS
        }
        self.execution_noise_half_vectors_drawn = {
            stream: 0 for stream in EXECUTION_NOISE_STREAMS
        }
        self.last_target_twin_reduction_gap = 0.0
        self.total_updates = 0

    def execution_noise_metadata(self) -> Dict[str, object]:
        """Return the exact channel-estimator semantics and its Q cost."""

        fixed_perturbations = (
            self.execution_noise.detach().cpu().tolist()
            if self.execution_noise is not None
            else None
        )
        resampled = self.config.execution_noise_scheme == "resampled_antithetic"
        return {
            "enabled": bool(self.config.marginalize_execution_noise),
            "distribution": "iid_uniform_minus_beta_plus_beta_per_action_dimension",
            "beta": float(self.config.execution_noise_beta),
            "sample_count": int(self.config.execution_noise_samples),
            "scheme": self.config.execution_noise_scheme,
            "twin_reduction": self.config.execution_noise_twin_reduction,
            "seed": int(self.config.execution_noise_seed),
            "stream_seeds": dict(self.execution_noise_stream_seeds),
            "reuse": (
                "resampled_independently_per_state_and_q_call"
                if resampled
                else "frozen_for_all_states_and_updates"
            ),
            "resampled_per_state_and_q_call": resampled,
            "dedicated_torch_generator": resampled,
            "approximation": (
                "antithetic_monte_carlo_of_the_known_channel"
                if resampled
                else "finite_antithetic_empirical_quadrature_of_the_known_channel"
            ),
            "fixed_action_perturbations": fixed_perturbations,
            "execution_noise_draw_calls": dict(self.execution_noise_draw_calls),
            "execution_noise_half_vectors_drawn": dict(
                self.execution_noise_half_vectors_drawn
            ),
            "checkpoint_contains_generator_state": resampled,
            "agent_restore_execution_noise_state_supported": resampled,
            "trainer_resume_restores_generator_state": False,
            "reproducibility_scope": (
                "continuous_run_same_seed_device_backend_and_call_order;"
                "exact_training_resume_not_implemented"
                if resampled
                else "continuous_run_fixed_points;exact_training_resume_not_implemented"
            ),
            "resume_limitation": (
                "train_td3bc_has_no_checkpoint_resume_path"
                if resampled
                else None
            ),
            "target_twin_q_rows_per_transition": int(
                self.config.execution_noise_samples
            ),
            "actor_q1_rows_per_transition_per_actor_update": int(
                self.config.execution_noise_samples
            ),
        }

    def normalize_observations(self, observations: torch.Tensor) -> torch.Tensor:
        return (observations - self.observation_mean) / self.observation_std

    @torch.no_grad()
    def _target_actions(
        self,
        normalized_next_observations: torch.Tensor,
        target_noise: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        if target_noise is None:
            target_noise = torch.randn(
                (
                    normalized_next_observations.shape[0],
                    self.config.action_dim,
                ),
                dtype=normalized_next_observations.dtype,
                device=normalized_next_observations.device,
            ) * (self.config.policy_noise * self.config.max_action)
        target_noise = target_noise.clamp(
            -self.config.noise_clip * self.config.max_action,
            self.config.noise_clip * self.config.max_action,
        )
        actions = self.actor_target(normalized_next_observations) + target_noise
        return actions.clamp(-self.config.max_action, self.config.max_action)

    def execution_action_samples(
        self, commands: torch.Tensor, stream: str = "actor"
    ) -> torch.Tensor:
        """Map ``[batch, action]`` commands to clipped physical actions.

        The returned shape is ``[batch, K, action]``.  The operation remains
        differentiable with respect to commands inside the action bounds, as
        required by the actor objective.
        """

        if commands.ndim != 2 or commands.shape[-1] != self.config.action_dim:
            raise ValueError(
                "commands must have shape [batch, action_dim], got "
                f"{tuple(commands.shape)}"
            )
        if stream not in EXECUTION_NOISE_STREAMS:
            raise ValueError(
                f"stream must be one of {EXECUTION_NOISE_STREAMS}, got {stream!r}"
            )
        if self.config.execution_noise_scheme == "fixed_antithetic":
            if self.execution_noise is None:
                raise AssertionError("fixed execution noise was not initialized")
            perturbations = self.execution_noise[None, :, :]
        else:
            if stream not in self.execution_noise_generators:
                raise AssertionError("resampled execution-noise RNG was not initialized")
            if self.config.execution_noise_beta == 0.0:
                perturbations = torch.zeros(
                    (
                        commands.shape[0],
                        self.config.execution_noise_samples,
                        self.config.action_dim,
                    ),
                    dtype=commands.dtype,
                    device=commands.device,
                )
                half_count = 0
            else:
                half_count = self.config.execution_noise_samples // 2
                half = torch.rand(
                    (commands.shape[0], half_count, self.config.action_dim),
                    generator=self.execution_noise_generators[stream],
                    dtype=commands.dtype,
                    device=commands.device,
                )
                half = (2.0 * half - 1.0) * self.config.execution_noise_beta
                perturbations = torch.cat((half, -half), dim=1)
            self.execution_noise_draw_calls[stream] += 1
            self.execution_noise_half_vectors_drawn[stream] += (
                commands.shape[0] * half_count
            )
        actions = commands[:, None, :] + perturbations
        return actions.clamp(-self.config.max_action, self.config.max_action)

    def _expanded_observations_and_actions(
        self,
        normalized_observations: torch.Tensor,
        commands: torch.Tensor,
        stream: str,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        if normalized_observations.ndim != 2:
            raise ValueError("normalized_observations must have rank two")
        if normalized_observations.shape[0] != commands.shape[0]:
            raise ValueError("observation and command batch sizes must match")
        physical_actions = self.execution_action_samples(commands, stream=stream)
        batch_size, sample_count, _ = physical_actions.shape
        expanded_observations = normalized_observations[:, None, :].expand(
            -1, sample_count, -1
        )
        return (
            expanded_observations.reshape(batch_size * sample_count, -1),
            physical_actions.reshape(batch_size * sample_count, -1),
        )

    def marginalized_q1(
        self,
        critic: TwinCritic,
        normalized_observations: torch.Tensor,
        commands: torch.Tensor,
    ) -> torch.Tensor:
        """Evaluate one critic under the fixed execution-noise quadrature."""

        expanded_observations, physical_actions = (
            self._expanded_observations_and_actions(
                normalized_observations, commands, stream="actor"
            )
        )
        batch_size = commands.shape[0]
        values = critic.q1_only(expanded_observations, physical_actions)
        return values.reshape(batch_size, self.config.execution_noise_samples).mean(
            dim=1
        )

    def marginalized_clipped_double_q(
        self,
        critic: TwinCritic,
        normalized_observations: torch.Tensor,
        commands: torch.Tensor,
    ) -> torch.Tensor:
        """Reduce twin Q after execution-channel marginalization.

        ``min_of_expectations`` is the default: each physical-action critic
        defines a command-value by averaging over the known channel, then TD3
        clipping is applied to those two command-values.
        ``expectation_of_min`` is retained as an explicitly more pessimistic
        control.  Their nonnegative difference is logged so that channel
        marginalization is not conflated with extra critic-disagreement
        pessimism.
        """

        expanded_observations, physical_actions = (
            self._expanded_observations_and_actions(
                normalized_observations, commands, stream="target"
            )
        )
        batch_size = commands.shape[0]
        q1, q2 = critic.both(expanded_observations, physical_actions)
        q1 = q1.reshape(batch_size, self.config.execution_noise_samples)
        q2 = q2.reshape(batch_size, self.config.execution_noise_samples)
        min_of_means = torch.minimum(q1.mean(dim=1), q2.mean(dim=1))
        mean_of_mins = torch.minimum(q1, q2).mean(dim=1)
        self.last_target_twin_reduction_gap = float(
            (min_of_means - mean_of_mins).detach().clamp_min(0.0).mean()
        )
        if self.config.execution_noise_twin_reduction == "min_of_expectations":
            return min_of_means
        if self.config.execution_noise_twin_reduction == "expectation_of_min":
            return mean_of_mins
        raise AssertionError("TD3BCConfig failed to validate twin reduction")

    @torch.no_grad()
    def compute_critic_target(
        self,
        batch: Dict[str, torch.Tensor],
        target_noise: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        next_observations = self.normalize_observations(batch["next_observations"])
        next_commands = self._target_actions(next_observations, target_noise)
        target_q = self.marginalized_clipped_double_q(
            self.critic_target, next_observations, next_commands
        )
        lambdas = batch["lambdas"]
        heuristic_next = batch["heuristic_next"]
        mixed_continuation = lambdas * heuristic_next + (1.0 - lambdas) * target_q
        return batch["rewards"] + (
            self.config.discount * (1.0 - batch["terminals"]) * mixed_continuation
        )

    def compute_actor_loss(
        self, normalized_observations: torch.Tensor, dataset_actions: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        policy_actions = self.actor(normalized_observations)
        policy_q = self.marginalized_q1(
            self.critic, normalized_observations, policy_actions
        )
        q_scale = self.config.alpha / policy_q.abs().mean().detach().clamp_min(
            self.config.q_scale_epsilon
        )
        behavior_cloning_loss = (policy_actions - dataset_actions).square().mean()
        actor_loss = -q_scale * policy_q.mean() + behavior_cloning_loss
        return actor_loss, q_scale, behavior_cloning_loss, policy_q.mean()

    def select_action_channels(
        self, batch: Dict[str, torch.Tensor]
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Return ``(critic_action, BC_action)`` for the configured control.

        Requiring both fields even for the standard control prevents a loader
        mistake from silently collapsing the two channels in a dual-action run.
        Shape validation is deliberately performed before any optimizer step.
        """

        if "executed_actions" not in batch or "commanded_actions" not in batch:
            raise KeyError(
                "batch must contain explicit executed_actions and commanded_actions"
            )
        executed = batch["executed_actions"]
        commanded = batch["commanded_actions"]
        if executed.shape != commanded.shape:
            raise ValueError(
                "executed_actions and commanded_actions must have identical shape"
            )
        if self.config.action_pairing == "executed_executed":
            return executed, executed
        if self.config.action_pairing == "commanded_commanded":
            return commanded, commanded
        if self.config.action_pairing == "executed_commanded":
            return executed, commanded
        raise AssertionError("TD3BCConfig validation failed to reject action pairing")

    def update(self, batch: Dict[str, torch.Tensor]) -> Dict[str, float]:
        self.total_updates += 1
        observations = self.normalize_observations(batch["observations"])
        critic_actions, behavior_cloning_actions = self.select_action_channels(batch)
        critic_target = self.compute_critic_target(batch)
        current_q1, current_q2 = self.critic.both(observations, critic_actions)
        critic_loss = (
            (current_q1 - critic_target).square().mean()
            + (current_q2 - critic_target).square().mean()
        )
        self.critic_optimizer.zero_grad(set_to_none=True)
        critic_loss.backward()
        self.critic_optimizer.step()

        metrics: Dict[str, float] = {
            "critic_loss": float(critic_loss.detach()),
            "q1_mean": float(current_q1.detach().mean()),
            "q2_mean": float(current_q2.detach().mean()),
            "q_target_mean": float(critic_target.detach().mean()),
            "heuristic_mean": float(batch["heuristic_next"].mean()),
            "hubl_lambda_mean": float(batch["lambdas"].mean()),
            "executed_commanded_action_mse": float(
                (batch["executed_actions"] - batch["commanded_actions"])
                .square()
                .mean()
            ),
            "critic_uses_commanded_action": float(
                self.config.action_pairing == "commanded_commanded"
            ),
            "bc_uses_commanded_action": float(
                self.config.action_pairing
                in ("commanded_commanded", "executed_commanded")
            ),
            "execution_noise_marginalized": float(
                self.config.marginalize_execution_noise
            ),
            "execution_noise_sample_count": float(
                self.config.execution_noise_samples
            ),
            "target_twin_reduction_swap_gap": float(
                self.last_target_twin_reduction_gap
            ),
            "actor_updated": 0.0,
        }

        if self.total_updates % self.config.policy_frequency == 0:
            actor_loss, q_scale, bc_loss, actor_q = self.compute_actor_loss(
                observations, behavior_cloning_actions
            )
            self.actor_optimizer.zero_grad(set_to_none=True)
            actor_loss.backward()
            self.actor_optimizer.step()
            self._soft_update(self.critic_target, self.critic)
            self._soft_update(self.actor_target, self.actor)
            metrics.update(
                {
                    "actor_updated": 1.0,
                    "actor_loss": float(actor_loss.detach()),
                    "behavior_cloning_loss": float(bc_loss.detach()),
                    "actor_q_mean": float(actor_q.detach()),
                    "actor_q_scale": float(q_scale.detach()),
                }
            )
        return metrics

    def _soft_update(self, target: nn.Module, source: nn.Module) -> None:
        with torch.no_grad():
            for target_parameter, source_parameter in zip(
                target.parameters(), source.parameters()
            ):
                target_parameter.mul_(1.0 - self.config.tau)
                target_parameter.add_(source_parameter, alpha=self.config.tau)

    @torch.no_grad()
    def act(
        self, observation: np.ndarray, action_low: np.ndarray, action_high: np.ndarray
    ) -> np.ndarray:
        tensor = torch.as_tensor(
            observation, dtype=torch.float32, device=self.device
        ).reshape(1, -1)
        normalized = self.normalize_observations(tensor)
        action = self.actor(normalized).squeeze(0).cpu().numpy()
        return np.clip(action, action_low, action_high)

    def checkpoint(self) -> Dict[str, object]:
        execution_noise_generator_states = {
            stream: generator.get_state()
            for stream, generator in self.execution_noise_generators.items()
        }
        return {
            "config": self.config.__dict__,
            "total_updates": self.total_updates,
            "observation_mean": self.observation_mean.detach().cpu(),
            "observation_std": self.observation_std.detach().cpu(),
            "execution_noise": (
                self.execution_noise.detach().cpu()
                if self.execution_noise is not None
                else None
            ),
            "execution_noise_generator_states": execution_noise_generator_states,
            "execution_noise_draw_calls": dict(self.execution_noise_draw_calls),
            "execution_noise_half_vectors_drawn": dict(
                self.execution_noise_half_vectors_drawn
            ),
            "actor": self.actor.state_dict(),
            "actor_target": self.actor_target.state_dict(),
            "critic": self.critic.state_dict(),
            "critic_target": self.critic_target.state_dict(),
            "actor_optimizer": self.actor_optimizer.state_dict(),
            "critic_optimizer": self.critic_optimizer.state_dict(),
        }

    def restore_execution_noise_state(self, checkpoint: Dict[str, object]) -> None:
        """Restore only the dedicated execution-channel sampling streams.

        This supports unit-level continuation of the channel estimator.  It is
        intentionally not advertised as complete training resume: the current
        trainer has no loader for networks, optimizers, minibatch RNG, global
        RNG, or TD3 smoothing RNG.
        """

        saved_config = checkpoint.get("config")
        if not isinstance(saved_config, dict):
            raise ValueError("checkpoint lacks TD3BCConfig metadata")
        for field in (
            "execution_noise_scheme",
            "execution_noise_beta",
            "execution_noise_samples",
            "execution_noise_seed",
        ):
            if saved_config.get(field) != getattr(self.config, field):
                raise ValueError(
                    f"checkpoint execution-noise config mismatch for {field}"
                )
        states = checkpoint.get("execution_noise_generator_states")
        if self.config.execution_noise_scheme != "resampled_antithetic":
            if states not in ({}, None):
                raise ValueError("fixed scheme checkpoint unexpectedly has RNG state")
            return
        if not isinstance(states, dict) or set(states) != set(EXECUTION_NOISE_STREAMS):
            raise ValueError("checkpoint lacks both execution-noise stream states")
        for stream in EXECUTION_NOISE_STREAMS:
            state = states[stream]
            if not isinstance(state, torch.Tensor):
                raise ValueError(f"invalid generator state for {stream}")
            self.execution_noise_generators[stream].set_state(state)
        draw_calls = checkpoint.get("execution_noise_draw_calls")
        half_vectors = checkpoint.get("execution_noise_half_vectors_drawn")
        if isinstance(draw_calls, dict):
            self.execution_noise_draw_calls = {
                stream: int(draw_calls[stream]) for stream in EXECUTION_NOISE_STREAMS
            }
        if isinstance(half_vectors, dict):
            self.execution_noise_half_vectors_drawn = {
                stream: int(half_vectors[stream])
                for stream in EXECUTION_NOISE_STREAMS
            }
